server.port=8080
skill.manager.base-url=http://localhost:8025
skill.manager.phone=9301
skill.manager.default-ttl-seconds=3600
skill.manager.gc-fixed-delay-millis=15000
skill.manager.queue-polling-enabled=false
skill.manager.queue-processing-enabled=true
skill.manager.queue-poll-fixed-delay-millis=60000
skill.manager.backend-url=http://localhost:8080
skill.manager.react-url=http://localhost:5173
skill.manager.llm-enabled=true
